on:
  schedule:
    - cron: "0 * * * *"
  push:
  pull_request:

name: iai beta toolchain benchmarks

jobs:
  release-version:
    name: (release) iai beta toolchain benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: beta
          override: true
      - run: sudo apt install -y valgrind
      - name: run beta benchmarks
        uses: actions-rs/cargo@v1
        with:
          command: bench
  main-branch-version:
    name: (main) iai beta toolchain benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: beta
          override: true
      - run: sudo apt install -y valgrind
      - run: mv Cargo.toml.main Cargo.toml
      - name: run beta benchmarks
        uses: actions-rs/cargo@v1
        with:
          command: bench
