on:
  schedule:
    - cron: "0 * * * *"
  push:
  pull_request:

name: iai nightly toolchain benchmarks

jobs:
  fmt:
    name: iai nightly toolchain benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - run: sudo apt install -y valgrind
      - uses: actions-rs/cargo@v1
        with:
          command: bench
